/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "MockDumber.h"

static const char* CMockString_Dumber_Checksum_Compute = "Dumber_Checksum_Compute";
static const char* CMockString_Dumber_Checksum_Verify = "Dumber_Checksum_Verify";
static const char* CMockString_Dumber_HexEncode = "Dumber_HexEncode";
static const char* CMockString_Dumber_XOR_Buffer = "Dumber_XOR_Buffer";
static const char* CMockString_buf_size = "buf_size";
static const char* CMockString_input = "input";
static const char* CMockString_key = "key";
static const char* CMockString_len = "len";
static const char* CMockString_message = "message";
static const char* CMockString_output = "output";

typedef struct _CMOCK_Dumber_XOR_Buffer_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  const uint8_t* Expected_input;
  size_t Expected_len;
  const char* Expected_key;
  uint8_t* Expected_output;

} CMOCK_Dumber_XOR_Buffer_CALL_INSTANCE;

typedef struct _CMOCK_Dumber_HexEncode_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  const uint8_t* Expected_input;
  size_t Expected_len;
  char* Expected_output;
  size_t Expected_buf_size;

} CMOCK_Dumber_HexEncode_CALL_INSTANCE;

typedef struct _CMOCK_Dumber_Checksum_Verify_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;
  const uint8_t* Expected_message;
  size_t Expected_len;
  const char* Expected_key;

} CMOCK_Dumber_Checksum_Verify_CALL_INSTANCE;

typedef struct _CMOCK_Dumber_Checksum_Compute_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;
  const uint8_t* Expected_message;
  size_t Expected_len;
  const char* Expected_key;

} CMOCK_Dumber_Checksum_Compute_CALL_INSTANCE;

static struct MockDumberInstance
{
  char Dumber_XOR_Buffer_IgnoreBool;
  char Dumber_XOR_Buffer_CallbackBool;
  CMOCK_Dumber_XOR_Buffer_CALLBACK Dumber_XOR_Buffer_CallbackFunctionPointer;
  int Dumber_XOR_Buffer_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE Dumber_XOR_Buffer_CallInstance;
  char Dumber_HexEncode_IgnoreBool;
  char Dumber_HexEncode_CallbackBool;
  CMOCK_Dumber_HexEncode_CALLBACK Dumber_HexEncode_CallbackFunctionPointer;
  int Dumber_HexEncode_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE Dumber_HexEncode_CallInstance;
  char Dumber_Checksum_Verify_IgnoreBool;
  bool Dumber_Checksum_Verify_FinalReturn;
  char Dumber_Checksum_Verify_CallbackBool;
  CMOCK_Dumber_Checksum_Verify_CALLBACK Dumber_Checksum_Verify_CallbackFunctionPointer;
  int Dumber_Checksum_Verify_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE Dumber_Checksum_Verify_CallInstance;
  char Dumber_Checksum_Compute_IgnoreBool;
  uint8_t Dumber_Checksum_Compute_FinalReturn;
  char Dumber_Checksum_Compute_CallbackBool;
  CMOCK_Dumber_Checksum_Compute_CALLBACK Dumber_Checksum_Compute_CallbackFunctionPointer;
  int Dumber_Checksum_Compute_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE Dumber_Checksum_Compute_CallInstance;
} Mock;


void MockDumber_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.Dumber_XOR_Buffer_CallInstance;
  if (Mock.Dumber_XOR_Buffer_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_Dumber_XOR_Buffer);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.Dumber_XOR_Buffer_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.Dumber_HexEncode_CallInstance;
  if (Mock.Dumber_HexEncode_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_Dumber_HexEncode);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.Dumber_HexEncode_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.Dumber_Checksum_Verify_CallInstance;
  if (Mock.Dumber_Checksum_Verify_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_Dumber_Checksum_Verify);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.Dumber_Checksum_Verify_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.Dumber_Checksum_Compute_CallInstance;
  if (Mock.Dumber_Checksum_Compute_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_Dumber_Checksum_Compute);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.Dumber_Checksum_Compute_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void MockDumber_Init(void)
{
  MockDumber_Destroy();
}

void MockDumber_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void Dumber_XOR_Buffer(const uint8_t* input, size_t len, const char* key, uint8_t* output)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Dumber_XOR_Buffer_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Dumber_XOR_Buffer);
  cmock_call_instance = (CMOCK_Dumber_XOR_Buffer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Dumber_XOR_Buffer_CallInstance);
  Mock.Dumber_XOR_Buffer_CallInstance = CMock_Guts_MemNext(Mock.Dumber_XOR_Buffer_CallInstance);
  if (Mock.Dumber_XOR_Buffer_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.Dumber_XOR_Buffer_CallbackBool &&
      Mock.Dumber_XOR_Buffer_CallbackFunctionPointer != NULL)
  {
    Mock.Dumber_XOR_Buffer_CallbackFunctionPointer(input, len, key, output, Mock.Dumber_XOR_Buffer_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_Dumber_XOR_Buffer,CMockString_input);
    if (cmock_call_instance->Expected_input == NULL)
      { UNITY_TEST_ASSERT_NULL(input, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_input, input, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_Dumber_XOR_Buffer,CMockString_len);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_len, &len, sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_Dumber_XOR_Buffer,CMockString_key);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_key, key, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_Dumber_XOR_Buffer,CMockString_output);
    if (cmock_call_instance->Expected_output == NULL)
      { UNITY_TEST_ASSERT_NULL(output, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_output, output, 1, cmock_line, CMockStringMismatch); }
  }
  if (Mock.Dumber_XOR_Buffer_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_Dumber_XOR_Buffer);
    Mock.Dumber_XOR_Buffer_CallbackFunctionPointer(input, len, key, output, Mock.Dumber_XOR_Buffer_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_Dumber_XOR_Buffer(CMOCK_Dumber_XOR_Buffer_CALL_INSTANCE* cmock_call_instance, const uint8_t* input, size_t len, const char* key, uint8_t* output);
void CMockExpectParameters_Dumber_XOR_Buffer(CMOCK_Dumber_XOR_Buffer_CALL_INSTANCE* cmock_call_instance, const uint8_t* input, size_t len, const char* key, uint8_t* output)
{
  cmock_call_instance->Expected_input = input;
  memcpy((void*)(&cmock_call_instance->Expected_len), (const void*)(&len),
         sizeof(size_t[sizeof(len) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_key = key;
  cmock_call_instance->Expected_output = output;
}

void Dumber_XOR_Buffer_CMockIgnore(void)
{
  Mock.Dumber_XOR_Buffer_IgnoreBool = (char)1;
}

void Dumber_XOR_Buffer_CMockStopIgnore(void)
{
  Mock.Dumber_XOR_Buffer_IgnoreBool = (char)0;
}

void Dumber_XOR_Buffer_CMockExpect(UNITY_LINE_TYPE cmock_line, const uint8_t* input, size_t len, const char* key, uint8_t* output)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Dumber_XOR_Buffer_CALL_INSTANCE));
  CMOCK_Dumber_XOR_Buffer_CALL_INSTANCE* cmock_call_instance = (CMOCK_Dumber_XOR_Buffer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Dumber_XOR_Buffer_CallInstance = CMock_Guts_MemChain(Mock.Dumber_XOR_Buffer_CallInstance, cmock_guts_index);
  Mock.Dumber_XOR_Buffer_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_Dumber_XOR_Buffer(cmock_call_instance, input, len, key, output);
}

void Dumber_XOR_Buffer_AddCallback(CMOCK_Dumber_XOR_Buffer_CALLBACK Callback)
{
  Mock.Dumber_XOR_Buffer_IgnoreBool = (char)0;
  Mock.Dumber_XOR_Buffer_CallbackBool = (char)1;
  Mock.Dumber_XOR_Buffer_CallbackFunctionPointer = Callback;
}

void Dumber_XOR_Buffer_Stub(CMOCK_Dumber_XOR_Buffer_CALLBACK Callback)
{
  Mock.Dumber_XOR_Buffer_IgnoreBool = (char)0;
  Mock.Dumber_XOR_Buffer_CallbackBool = (char)0;
  Mock.Dumber_XOR_Buffer_CallbackFunctionPointer = Callback;
}

void Dumber_HexEncode(const uint8_t* input, size_t len, char* output, size_t buf_size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Dumber_HexEncode_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Dumber_HexEncode);
  cmock_call_instance = (CMOCK_Dumber_HexEncode_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Dumber_HexEncode_CallInstance);
  Mock.Dumber_HexEncode_CallInstance = CMock_Guts_MemNext(Mock.Dumber_HexEncode_CallInstance);
  if (Mock.Dumber_HexEncode_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.Dumber_HexEncode_CallbackBool &&
      Mock.Dumber_HexEncode_CallbackFunctionPointer != NULL)
  {
    Mock.Dumber_HexEncode_CallbackFunctionPointer(input, len, output, buf_size, Mock.Dumber_HexEncode_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_Dumber_HexEncode,CMockString_input);
    if (cmock_call_instance->Expected_input == NULL)
      { UNITY_TEST_ASSERT_NULL(input, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_input, input, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_Dumber_HexEncode,CMockString_len);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_len, &len, sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_Dumber_HexEncode,CMockString_output);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_output, output, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_Dumber_HexEncode,CMockString_buf_size);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_buf_size, &buf_size, sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  if (Mock.Dumber_HexEncode_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_Dumber_HexEncode);
    Mock.Dumber_HexEncode_CallbackFunctionPointer(input, len, output, buf_size, Mock.Dumber_HexEncode_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_Dumber_HexEncode(CMOCK_Dumber_HexEncode_CALL_INSTANCE* cmock_call_instance, const uint8_t* input, size_t len, char* output, size_t buf_size);
void CMockExpectParameters_Dumber_HexEncode(CMOCK_Dumber_HexEncode_CALL_INSTANCE* cmock_call_instance, const uint8_t* input, size_t len, char* output, size_t buf_size)
{
  cmock_call_instance->Expected_input = input;
  memcpy((void*)(&cmock_call_instance->Expected_len), (const void*)(&len),
         sizeof(size_t[sizeof(len) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_output = output;
  memcpy((void*)(&cmock_call_instance->Expected_buf_size), (const void*)(&buf_size),
         sizeof(size_t[sizeof(buf_size) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
}

void Dumber_HexEncode_CMockIgnore(void)
{
  Mock.Dumber_HexEncode_IgnoreBool = (char)1;
}

void Dumber_HexEncode_CMockStopIgnore(void)
{
  Mock.Dumber_HexEncode_IgnoreBool = (char)0;
}

void Dumber_HexEncode_CMockExpect(UNITY_LINE_TYPE cmock_line, const uint8_t* input, size_t len, char* output, size_t buf_size)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Dumber_HexEncode_CALL_INSTANCE));
  CMOCK_Dumber_HexEncode_CALL_INSTANCE* cmock_call_instance = (CMOCK_Dumber_HexEncode_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Dumber_HexEncode_CallInstance = CMock_Guts_MemChain(Mock.Dumber_HexEncode_CallInstance, cmock_guts_index);
  Mock.Dumber_HexEncode_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_Dumber_HexEncode(cmock_call_instance, input, len, output, buf_size);
}

void Dumber_HexEncode_AddCallback(CMOCK_Dumber_HexEncode_CALLBACK Callback)
{
  Mock.Dumber_HexEncode_IgnoreBool = (char)0;
  Mock.Dumber_HexEncode_CallbackBool = (char)1;
  Mock.Dumber_HexEncode_CallbackFunctionPointer = Callback;
}

void Dumber_HexEncode_Stub(CMOCK_Dumber_HexEncode_CALLBACK Callback)
{
  Mock.Dumber_HexEncode_IgnoreBool = (char)0;
  Mock.Dumber_HexEncode_CallbackBool = (char)0;
  Mock.Dumber_HexEncode_CallbackFunctionPointer = Callback;
}

bool Dumber_Checksum_Verify(const uint8_t* message, size_t len, const char* key)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Dumber_Checksum_Verify_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Dumber_Checksum_Verify);
  cmock_call_instance = (CMOCK_Dumber_Checksum_Verify_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Dumber_Checksum_Verify_CallInstance);
  Mock.Dumber_Checksum_Verify_CallInstance = CMock_Guts_MemNext(Mock.Dumber_Checksum_Verify_CallInstance);
  if (Mock.Dumber_Checksum_Verify_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.Dumber_Checksum_Verify_FinalReturn;
    Mock.Dumber_Checksum_Verify_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.Dumber_Checksum_Verify_CallbackBool &&
      Mock.Dumber_Checksum_Verify_CallbackFunctionPointer != NULL)
  {
    bool cmock_cb_ret = Mock.Dumber_Checksum_Verify_CallbackFunctionPointer(message, len, key, Mock.Dumber_Checksum_Verify_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_Dumber_Checksum_Verify,CMockString_message);
    if (cmock_call_instance->Expected_message == NULL)
      { UNITY_TEST_ASSERT_NULL(message, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_message, message, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_Dumber_Checksum_Verify,CMockString_len);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_len, &len, sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_Dumber_Checksum_Verify,CMockString_key);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_key, key, cmock_line, CMockStringMismatch);
  }
  if (Mock.Dumber_Checksum_Verify_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_Dumber_Checksum_Verify);
    cmock_call_instance->ReturnVal = Mock.Dumber_Checksum_Verify_CallbackFunctionPointer(message, len, key, Mock.Dumber_Checksum_Verify_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_Dumber_Checksum_Verify(CMOCK_Dumber_Checksum_Verify_CALL_INSTANCE* cmock_call_instance, const uint8_t* message, size_t len, const char* key);
void CMockExpectParameters_Dumber_Checksum_Verify(CMOCK_Dumber_Checksum_Verify_CALL_INSTANCE* cmock_call_instance, const uint8_t* message, size_t len, const char* key)
{
  cmock_call_instance->Expected_message = message;
  memcpy((void*)(&cmock_call_instance->Expected_len), (const void*)(&len),
         sizeof(size_t[sizeof(len) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_key = key;
}

void Dumber_Checksum_Verify_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Dumber_Checksum_Verify_CALL_INSTANCE));
  CMOCK_Dumber_Checksum_Verify_CALL_INSTANCE* cmock_call_instance = (CMOCK_Dumber_Checksum_Verify_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Dumber_Checksum_Verify_CallInstance = CMock_Guts_MemChain(Mock.Dumber_Checksum_Verify_CallInstance, cmock_guts_index);
  Mock.Dumber_Checksum_Verify_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.Dumber_Checksum_Verify_IgnoreBool = (char)1;
}

void Dumber_Checksum_Verify_CMockStopIgnore(void)
{
  if(Mock.Dumber_Checksum_Verify_IgnoreBool)
    Mock.Dumber_Checksum_Verify_CallInstance = CMock_Guts_MemNext(Mock.Dumber_Checksum_Verify_CallInstance);
  Mock.Dumber_Checksum_Verify_IgnoreBool = (char)0;
}

void Dumber_Checksum_Verify_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const uint8_t* message, size_t len, const char* key, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Dumber_Checksum_Verify_CALL_INSTANCE));
  CMOCK_Dumber_Checksum_Verify_CALL_INSTANCE* cmock_call_instance = (CMOCK_Dumber_Checksum_Verify_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Dumber_Checksum_Verify_CallInstance = CMock_Guts_MemChain(Mock.Dumber_Checksum_Verify_CallInstance, cmock_guts_index);
  Mock.Dumber_Checksum_Verify_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_Dumber_Checksum_Verify(cmock_call_instance, message, len, key);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void Dumber_Checksum_Verify_AddCallback(CMOCK_Dumber_Checksum_Verify_CALLBACK Callback)
{
  Mock.Dumber_Checksum_Verify_IgnoreBool = (char)0;
  Mock.Dumber_Checksum_Verify_CallbackBool = (char)1;
  Mock.Dumber_Checksum_Verify_CallbackFunctionPointer = Callback;
}

void Dumber_Checksum_Verify_Stub(CMOCK_Dumber_Checksum_Verify_CALLBACK Callback)
{
  Mock.Dumber_Checksum_Verify_IgnoreBool = (char)0;
  Mock.Dumber_Checksum_Verify_CallbackBool = (char)0;
  Mock.Dumber_Checksum_Verify_CallbackFunctionPointer = Callback;
}

uint8_t Dumber_Checksum_Compute(const uint8_t* message, size_t len, const char* key)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Dumber_Checksum_Compute_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Dumber_Checksum_Compute);
  cmock_call_instance = (CMOCK_Dumber_Checksum_Compute_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Dumber_Checksum_Compute_CallInstance);
  Mock.Dumber_Checksum_Compute_CallInstance = CMock_Guts_MemNext(Mock.Dumber_Checksum_Compute_CallInstance);
  if (Mock.Dumber_Checksum_Compute_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.Dumber_Checksum_Compute_FinalReturn;
    Mock.Dumber_Checksum_Compute_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.Dumber_Checksum_Compute_CallbackBool &&
      Mock.Dumber_Checksum_Compute_CallbackFunctionPointer != NULL)
  {
    uint8_t cmock_cb_ret = Mock.Dumber_Checksum_Compute_CallbackFunctionPointer(message, len, key, Mock.Dumber_Checksum_Compute_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_Dumber_Checksum_Compute,CMockString_message);
    if (cmock_call_instance->Expected_message == NULL)
      { UNITY_TEST_ASSERT_NULL(message, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_message, message, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_Dumber_Checksum_Compute,CMockString_len);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_len, &len, sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_Dumber_Checksum_Compute,CMockString_key);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_key, key, cmock_line, CMockStringMismatch);
  }
  if (Mock.Dumber_Checksum_Compute_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_Dumber_Checksum_Compute);
    cmock_call_instance->ReturnVal = Mock.Dumber_Checksum_Compute_CallbackFunctionPointer(message, len, key, Mock.Dumber_Checksum_Compute_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_Dumber_Checksum_Compute(CMOCK_Dumber_Checksum_Compute_CALL_INSTANCE* cmock_call_instance, const uint8_t* message, size_t len, const char* key);
void CMockExpectParameters_Dumber_Checksum_Compute(CMOCK_Dumber_Checksum_Compute_CALL_INSTANCE* cmock_call_instance, const uint8_t* message, size_t len, const char* key)
{
  cmock_call_instance->Expected_message = message;
  memcpy((void*)(&cmock_call_instance->Expected_len), (const void*)(&len),
         sizeof(size_t[sizeof(len) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_key = key;
}

void Dumber_Checksum_Compute_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Dumber_Checksum_Compute_CALL_INSTANCE));
  CMOCK_Dumber_Checksum_Compute_CALL_INSTANCE* cmock_call_instance = (CMOCK_Dumber_Checksum_Compute_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Dumber_Checksum_Compute_CallInstance = CMock_Guts_MemChain(Mock.Dumber_Checksum_Compute_CallInstance, cmock_guts_index);
  Mock.Dumber_Checksum_Compute_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.Dumber_Checksum_Compute_IgnoreBool = (char)1;
}

void Dumber_Checksum_Compute_CMockStopIgnore(void)
{
  if(Mock.Dumber_Checksum_Compute_IgnoreBool)
    Mock.Dumber_Checksum_Compute_CallInstance = CMock_Guts_MemNext(Mock.Dumber_Checksum_Compute_CallInstance);
  Mock.Dumber_Checksum_Compute_IgnoreBool = (char)0;
}

void Dumber_Checksum_Compute_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const uint8_t* message, size_t len, const char* key, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Dumber_Checksum_Compute_CALL_INSTANCE));
  CMOCK_Dumber_Checksum_Compute_CALL_INSTANCE* cmock_call_instance = (CMOCK_Dumber_Checksum_Compute_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Dumber_Checksum_Compute_CallInstance = CMock_Guts_MemChain(Mock.Dumber_Checksum_Compute_CallInstance, cmock_guts_index);
  Mock.Dumber_Checksum_Compute_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_Dumber_Checksum_Compute(cmock_call_instance, message, len, key);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void Dumber_Checksum_Compute_AddCallback(CMOCK_Dumber_Checksum_Compute_CALLBACK Callback)
{
  Mock.Dumber_Checksum_Compute_IgnoreBool = (char)0;
  Mock.Dumber_Checksum_Compute_CallbackBool = (char)1;
  Mock.Dumber_Checksum_Compute_CallbackFunctionPointer = Callback;
}

void Dumber_Checksum_Compute_Stub(CMOCK_Dumber_Checksum_Compute_CALLBACK Callback)
{
  Mock.Dumber_Checksum_Compute_IgnoreBool = (char)0;
  Mock.Dumber_Checksum_Compute_CallbackBool = (char)0;
  Mock.Dumber_Checksum_Compute_CallbackFunctionPointer = Callback;
}

