/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKDUMBER_H
#define _MOCKDUMBER_H

#include "unity.h"
#include "Dumber.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void MockDumber_Init(void);
void MockDumber_Destroy(void);
void MockDumber_Verify(void);




#define Dumber_XOR_Buffer_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("Dumber_XOR_Buffer requires _Ignore (not AndReturn)");
#define Dumber_XOR_Buffer_Ignore() Dumber_XOR_Buffer_CMockIgnore()
void Dumber_XOR_Buffer_CMockIgnore(void);
#define Dumber_XOR_Buffer_StopIgnore() Dumber_XOR_Buffer_CMockStopIgnore()
void Dumber_XOR_Buffer_CMockStopIgnore(void);
#define Dumber_XOR_Buffer_ExpectAndReturn(input, len, key, output, cmock_retval) TEST_FAIL_MESSAGE("Dumber_XOR_Buffer requires _Expect (not AndReturn)");
#define Dumber_XOR_Buffer_Expect(input, len, key, output) Dumber_XOR_Buffer_CMockExpect(__LINE__, input, len, key, output)
void Dumber_XOR_Buffer_CMockExpect(UNITY_LINE_TYPE cmock_line, const uint8_t* input, size_t len, const char* key, uint8_t* output);
typedef void (* CMOCK_Dumber_XOR_Buffer_CALLBACK)(const uint8_t* input, size_t len, const char* key, uint8_t* output, int cmock_num_calls);
void Dumber_XOR_Buffer_AddCallback(CMOCK_Dumber_XOR_Buffer_CALLBACK Callback);
void Dumber_XOR_Buffer_Stub(CMOCK_Dumber_XOR_Buffer_CALLBACK Callback);
#define Dumber_XOR_Buffer_StubWithCallback Dumber_XOR_Buffer_Stub
#define Dumber_HexEncode_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("Dumber_HexEncode requires _Ignore (not AndReturn)");
#define Dumber_HexEncode_Ignore() Dumber_HexEncode_CMockIgnore()
void Dumber_HexEncode_CMockIgnore(void);
#define Dumber_HexEncode_StopIgnore() Dumber_HexEncode_CMockStopIgnore()
void Dumber_HexEncode_CMockStopIgnore(void);
#define Dumber_HexEncode_ExpectAndReturn(input, len, output, buf_size, cmock_retval) TEST_FAIL_MESSAGE("Dumber_HexEncode requires _Expect (not AndReturn)");
#define Dumber_HexEncode_Expect(input, len, output, buf_size) Dumber_HexEncode_CMockExpect(__LINE__, input, len, output, buf_size)
void Dumber_HexEncode_CMockExpect(UNITY_LINE_TYPE cmock_line, const uint8_t* input, size_t len, char* output, size_t buf_size);
typedef void (* CMOCK_Dumber_HexEncode_CALLBACK)(const uint8_t* input, size_t len, char* output, size_t buf_size, int cmock_num_calls);
void Dumber_HexEncode_AddCallback(CMOCK_Dumber_HexEncode_CALLBACK Callback);
void Dumber_HexEncode_Stub(CMOCK_Dumber_HexEncode_CALLBACK Callback);
#define Dumber_HexEncode_StubWithCallback Dumber_HexEncode_Stub
#define Dumber_Checksum_Verify_Ignore() TEST_FAIL_MESSAGE("Dumber_Checksum_Verify requires _IgnoreAndReturn");
#define Dumber_Checksum_Verify_IgnoreAndReturn(cmock_retval) Dumber_Checksum_Verify_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void Dumber_Checksum_Verify_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define Dumber_Checksum_Verify_StopIgnore() Dumber_Checksum_Verify_CMockStopIgnore()
void Dumber_Checksum_Verify_CMockStopIgnore(void);
#define Dumber_Checksum_Verify_Expect(message, len, key) TEST_FAIL_MESSAGE("Dumber_Checksum_Verify requires _ExpectAndReturn");
#define Dumber_Checksum_Verify_ExpectAndReturn(message, len, key, cmock_retval) Dumber_Checksum_Verify_CMockExpectAndReturn(__LINE__, message, len, key, cmock_retval)
void Dumber_Checksum_Verify_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const uint8_t* message, size_t len, const char* key, bool cmock_to_return);
typedef bool (* CMOCK_Dumber_Checksum_Verify_CALLBACK)(const uint8_t* message, size_t len, const char* key, int cmock_num_calls);
void Dumber_Checksum_Verify_AddCallback(CMOCK_Dumber_Checksum_Verify_CALLBACK Callback);
void Dumber_Checksum_Verify_Stub(CMOCK_Dumber_Checksum_Verify_CALLBACK Callback);
#define Dumber_Checksum_Verify_StubWithCallback Dumber_Checksum_Verify_Stub
#define Dumber_Checksum_Compute_Ignore() TEST_FAIL_MESSAGE("Dumber_Checksum_Compute requires _IgnoreAndReturn");
#define Dumber_Checksum_Compute_IgnoreAndReturn(cmock_retval) Dumber_Checksum_Compute_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void Dumber_Checksum_Compute_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define Dumber_Checksum_Compute_StopIgnore() Dumber_Checksum_Compute_CMockStopIgnore()
void Dumber_Checksum_Compute_CMockStopIgnore(void);
#define Dumber_Checksum_Compute_Expect(message, len, key) TEST_FAIL_MESSAGE("Dumber_Checksum_Compute requires _ExpectAndReturn");
#define Dumber_Checksum_Compute_ExpectAndReturn(message, len, key, cmock_retval) Dumber_Checksum_Compute_CMockExpectAndReturn(__LINE__, message, len, key, cmock_retval)
void Dumber_Checksum_Compute_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const uint8_t* message, size_t len, const char* key, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_Dumber_Checksum_Compute_CALLBACK)(const uint8_t* message, size_t len, const char* key, int cmock_num_calls);
void Dumber_Checksum_Compute_AddCallback(CMOCK_Dumber_Checksum_Compute_CALLBACK Callback);
void Dumber_Checksum_Compute_Stub(CMOCK_Dumber_Checksum_Compute_CALLBACK Callback);
#define Dumber_Checksum_Compute_StubWithCallback Dumber_Checksum_Compute_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
